algoritmo "Identificador de Números (Par ou Ímpar)"

var

numeroNumero, numeroDigitado : inteiro

inicio

escreva("Digite um número: ")
leia(numeroDigitado)

escolha (numeroDigitado)
    caso (2)
        escreval("É par!")
    caso (4)
        escreval("É par!")
    caso (6)
        escreval("É par!")
    caso (8)
        escreval("É par!")
    outrocaso
        escreval("É ímpar!")
fimescolha

fimalgoritmo

